### ISSUE TITLE
azurecommunity.pl down

### ISSUE THREAD

**Issue by gondar** [AzureCommunityPL/group#73]
It's returning 404 which isn't very helpful.
<img width="1438" alt="Screenshot 2020-09-18 at 14 49 51" src="https://user-images.githubusercontent.com/252896/93599377-55fd7d80-f9be-11ea-92e9-15553e4c99f4.png">

**Comment by kaluzaaa** [comment]
Prace w toku ;-) - https://github.com/AzureCommunityPL/azurecommunitypl.github.io/issues
